configfile:
    "config/config.yml"

workdir:
    config.get("workdir", ".")


include:
    "rules/common.smk"


CTX = build_workflow_context(config)
print_workflow_summary(CTX)

OUTDIR = PATHS.outdir
ENV = "../envs/chipseq.yml"

MODE = CTX.mode
SAMPLES = CTX.samples
SAMPLE_PATTERN = CTX.sample_pattern
TREATMENTS = CTX.treatments
TREATMENT_PATTERN = CTX.treatment_pattern

USE_POOLED_CONTROL = CTX.use_pooled_control
POOLED_CONTROL_PATTERN = CTX.pooled_control_pattern
HAS_EFFECTIVE_CONTROL = CTX.has_effective_control
EFFECTIVE_CONTROLS = CTX.effective_controls

CALL_PEAK_MODES = CTX.call_peak_modes
CALL_PEAK_TYPES = CTX.call_peak_types
REPLICATE_GROUPS = CTX.replicate_groups

ENABLE_DEEPTOOLS_PROFILE = CTX.enable_deeptools_profile
ENABLE_CHIPQC = CTX.enable_chipqc
ENABLE_HOMER = CTX.enable_homer

CHIPQC_PEAK_MODE = CTX.chipqc_peak_mode
CHIPQC_PEAK_TYPE = CTX.chipqc_peak_type
HOMER_PEAK_MODE = CTX.homer_peak_mode
HOMER_PEAK_TYPE = CTX.homer_peak_type
HOMER_RESULT_TAG = CTX.homer_result_tag


include:
    "rules/preprocess.smk"

include:
    "rules/peak_calling.smk"

include:
    "rules/qc.smk"

include:
    "rules/homer.smk"


rule all:
    input:
        all_outputs(CTX)
