configfile: "config/config.yml"

shell.prefix('[ -n "${{CONDA_PREFIX:-}}" ] && export PATH="${{CONDA_PREFIX}}/bin:$PATH"; ')

include: "rules/common.smk"

rule all:
    input:
        f"{OUTDIR}/lncrna/candidate_lncRNA.gtf",
        f"{OUTDIR}/lncrna/candidate_lncRNA.fa",
        f"{OUTDIR}/lncrna/candidate_lncRNA.summary.tsv",
        f"{OUTDIR}/lncrna/high_confidence_lncRNA.gtf",
        f"{OUTDIR}/lncrna/high_confidence_lncRNA.fa",
        f"{OUTDIR}/lncrna/high_confidence_lncRNA.summary.tsv",
        f"{OUTDIR}/lncrna/coding_filter/orf_metrics.tsv",
        f"{OUTDIR}/matrix/gene_counts.tsv",
        f"{OUTDIR}/matrix/gene_fpkm.tsv",
        f"{OUTDIR}/matrix/gene_tpm.tsv",
        f"{OUTDIR}/matrix/gene_length.tsv",
        f"{OUTDIR}/matrix/lncrna_counts.tsv",
        f"{OUTDIR}/matrix/lncrna_fpkm.tsv",
        f"{OUTDIR}/matrix/lncrna_tpm.tsv",
        f"{OUTDIR}/matrix/lncrna_length.tsv",
        expand(f"{OUTDIR}/bam/{{sample}}.sorted.bam", sample=SAMPLES),
        expand(f"{OUTDIR}/bam/{{sample}}.sorted.bam.bai", sample=SAMPLES),
        expand(f"{OUTDIR}/bigwig/{{sample}}.bw", sample=SAMPLES),
        f"{OUTDIR}/report/multiqc_report.html"

include: "rules/trim.smk"
include: "rules/align_star.smk"
include: "rules/assemble_stringtie.smk"
include: "rules/lncrna_filter.smk"
include: "rules/coding_filter.smk"
include: "rules/count_lncrna.smk"
include: "rules/matrix.smk"
include: "rules/bigwig.smk"
include: "rules/report.smk"
